---
title: "STAT Check Test"
author: "Justin C. Eldridge"
format: pdf
editor: visual
---

# Statcheck Test

```{r}
#Install the appropriate packages

#install.packages("statcheck")
library(statcheck)
#install.packages("pdftools")
library(pdftools)
```

Try it on a raw text string as a test

```{r}

txt <- "blablabla the effect was very significant (t(48) = 1.02, p < .05)"
statcheck(txt)
```

Try it on a pdf

```{r}
#Try setting the working directory


#lines <- readLines("Test PDFs/nuijten2015.txt")

#statcheck(lines)

checkPDF("Test PDFs/nuijten2015.pdf")


checkPDF("Test PDFs/s13428-025-02599-1.pdf")
checkHTML("Test PDFs/s13428-025-02599-1.pdf")
text2 <-pdf_text("Test PDFs/s13428-025-02599-1.pdf")


statcheck(text2)

checkPDF("Test PDFs/s13428-018-1147-z.pdf")


library(pdftools)
text <- pdf_text("Test PDFs/s13428-018-1147-z.pdf")
cat(text[1:13])  # Print first page to check

statcheck(text)


text3 <- pdf_text("Test PDFs/xge-a0030830.pdf")

statcheck(text3)

#checkPDF("\\Test PDFs\\Nkomo et al. - 2006 - Burden of valvular heart diseases a population-ba.pdf")


```

```{r}
test_df <-statcheck(c(text, text2, text3))
```
